from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        '''
        You are given two strings s and t.

        String t is generated by random shuffling string s 
        and then add one more letter at a random position.

        Return the letter that was added to t.

        '''       
        return next((Counter(t) - Counter(s)).elements())


    def findTheDifference2(self, s: str, t: str) -> str:
        from operator import xor
        from functools import reduce

        return chr(reduce(xor, map(ord, s+t)))



test = Solution()
s = "abcd"
t = "abcde"
ans = test.findTheDifference2(s, t)
print(ans)